
package org.example.dredge.code;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.14
 * 2021-07-02T17:02:06.220+08:00
 * Generated source version: 3.2.14
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.review.km.kmss.landray.com/")
public class Exception_Exception extends java.lang.Exception {

    private Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public Exception getFaultInfo() {
        return this.exception;
    }
}
